modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="zirfps"
version="1.0.0"
displayName="ZirFPS"
authors="ZirFPS"
description='''
Client-side optimization mod for Minecraft 1.14.4.
Features: Entity Culling, Dynamic FPS.
Boosts FPS by skipping invisible entities and reducing background load.
'''

[[dependencies.zirfps]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.zirfps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="CLIENT"
